#---------------------------------------------------------#

name: dik
description: nuovo progetto di app-development
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

#---------------------------------------------------------#

environment:
  sdk: '>=2.19.2 <3.0.0'

#---------------------------------------------------------#

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0
  google_fonts: ^4.0.3
  flutter_staggered_animations: ^1.1.1
  blurrycontainer: ^1.0.2
  flutter_slider_drawer: ^2.1.3
  infinite_scroll_pagination: ^3.2.0
  line_awesome_flutter: ^2.0.0
  infinite_scroll: ^1.1.1
  paginated_search_bar: ^1.1.2
  animations: ^2.0.8
  image_picker: ^0.8.9
  image_cropper: ^5.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  image: ^4.0.17
  palette_generator: ^0.3.3+2
  flutter_swipe_detector: ^2.0.0
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  interval_time_picker: ^2.0.0+5
  

#---------------------------------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # serve a mettere l'icona dell'app
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

#---------------------------------------------------------#

# Flutter packages

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_forefround.png"
  #adaptive_icon_background: "#090c15"

#---------------------------------------------------------#

flutter:

  assets:
    - assets/papera.jpg
    - assets/immagine di profilo.jpg
    - assets/prova1.jpg
    - assets/prova2.jpg
    - assets/prova3.jpg
    - assets/prova4.png
    - assets/black.jpg
    - assets/icons/

  fonts:
  - family: Lobster 
    fonts:
    - asset: assets/google_fonts/Lobster-Regular.ttf
  - family: Gelion Bold
    fonts:
    - asset: assets/fonts/Gelion Bold.ttf
  - family: Gelion Medium
    fonts:
    - asset: assets/fonts/Gelion Medium.ttf

  # questa linea inserisce il design di alcune classi di Icone come il "+" della versione base 
  uses-material-design: true


  # variabnti di assets di icone: https://flutter.dev/assets-and-images/#resolution-aware
  # come aggiungere i pacchetti di assets: https://flutter.dev/assets-and-images/#from-packages

  # dettagli sui pacchetti di font: https://flutter.dev/custom-fonts/#from-packages 

#---------------------------------------------------------#