// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXJgGiC0BEREcFjWuBCzW2uLWTEeQNa6E',
    appId: '1:133433635467:web:bdda9fa9fc6baacb33da8e',
    messagingSenderId: '133433635467',
    projectId: 'dik-project',
    authDomain: 'dik-project.firebaseapp.com',
    storageBucket: 'dik-project.appspot.com',
    measurementId: 'G-SWD3V87Q15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5PgONRG7Id6e7ORHwRh8i5DD0SrY9OM',
    appId: '1:133433635467:android:0c4ddac2fb9d18d133da8e',
    messagingSenderId: '133433635467',
    projectId: 'dik-project',
    storageBucket: 'dik-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdV7deLJPSRFaeXWSgycsM5vluS3bRsK4',
    appId: '1:133433635467:ios:f071025aabefdd1c33da8e',
    messagingSenderId: '133433635467',
    projectId: 'dik-project',
    storageBucket: 'dik-project.appspot.com',
    iosClientId: '133433635467-9pf9uku5855m64b2jl9cneufoojsj6qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdV7deLJPSRFaeXWSgycsM5vluS3bRsK4',
    appId: '1:133433635467:ios:f071025aabefdd1c33da8e',
    messagingSenderId: '133433635467',
    projectId: 'dik-project',
    storageBucket: 'dik-project.appspot.com',
    iosClientId: '133433635467-9pf9uku5855m64b2jl9cneufoojsj6qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dik',
  );
}
