// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMyZnaYfzy_Rp6YUGcACPE5CoKYo6QWlE',
    appId: '1:43969926316:web:87515a8f99e4bf749afb09',
    messagingSenderId: '43969926316',
    projectId: 'dikorp-393116',
    authDomain: 'dikorp-393116.firebaseapp.com',
    storageBucket: 'dikorp-393116.appspot.com',
    measurementId: 'G-Z96877JG1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmOILGqn4zBANaIXfcx7PXtijSyRLeG8',
    appId: '1:43969926316:android:9a45f614e0f066539afb09',
    messagingSenderId: '43969926316',
    projectId: 'dikorp-393116',
    storageBucket: 'dikorp-393116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTIks_myfxyCO5jwgPJ-kzneEP1IBcOH8',
    appId: '1:43969926316:ios:8d8030845baeecb69afb09',
    messagingSenderId: '43969926316',
    projectId: 'dikorp-393116',
    storageBucket: 'dikorp-393116.appspot.com',
    iosClientId: '43969926316-m73qffkf87dk3cmccm14qrov97h516h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTIks_myfxyCO5jwgPJ-kzneEP1IBcOH8',
    appId: '1:43969926316:ios:8d8030845baeecb69afb09',
    messagingSenderId: '43969926316',
    projectId: 'dikorp-393116',
    storageBucket: 'dikorp-393116.appspot.com',
    iosClientId: '43969926316-m73qffkf87dk3cmccm14qrov97h516h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dik',
  );
}
